### PR TITLE
add payment method operations

### PR DESCRIPTION
**Pull request by otaviosoares**
Depends on #7 

Add some payment method ops:

- Add
- Remove
- Set Default
- Retrieve
- List

### CODE REVIEW

**Comment by pierre** [comment]
Awesome! 🏆 

Let's iterate on https://github.com/killbill/killbill-client-js/pull/7 first (to make it easier to review this one).

Also, are all the tests passing for you? I'm getting the following error:

```
  28 passing (8s)
  1 failing

  1) Subscription Resource update should update subscription:

      actual expected

      "SuperStandard"
```

(it could be unrelated to your changes and/or caused by my Kill Bill configuration -- just curious if you are seeing this too)

**Comment by otaviosoares** [comment]
I was getting the same error even before I made the changes.

I haven't look at it because I thought it was related to different data on my database. Since that's not the case I'm going to take a look.

**Comment by otaviosoares** [comment]
@pierre I've found the reason the test wasn't passing. All green now.

**Comment by pierre** [comment]
Thanks!

**Pull request merged**
